import contextlib
import datetime
import os
import platform
import re
import shlex
import subprocess
import sys
import webbrowser
from pathlib import Path


def get_project_root():
    return Path(__file__).parent.resolve()


def bootstrap():
    """
    Called when first non-standard lib import fails.

    Given uv is installed, we need at least typer and rich to use this script.
    """
    if not (Path.cwd() / ".venv").exists():
        print("No .venv found, creating one using uv...")
        subprocess.run(["uv", "venv", ".venv"], check=True)
        print("Please activate the virtual environment and run the script again.")
        sys.exit(1)

    print("Sync requirements via uv...")
    subprocess.run(["uv", "sync"], check=True)


try:
    import typer
except ImportError:
    bootstrap()
    import typer

from rich import print  # noqa

cli = typer.Typer()


def get_pythonpath():
    """Add project root and model directory to string"""
    project_root = str(get_project_root())
    model_root = str(Path(__file__).parent / "model")
    return f"{project_root}:{model_root}"


def env_with_pythonpath():
    """Get en environment dict with includes PYTHONPATH"""
    env = os.environ.copy()
    env["PYTHONPATH"] = get_pythonpath()
    return env


@cli.command()
def mypy():
    """Run Mypy (configured in pyproject.toml)"""
    subprocess.call(["mypy", "."])


@cli.command()
def test():
    subprocess.call(["python", "-m", "pytest"], env=env_with_pythonpath())


@cli.command()
def coverage():
    """
    Run and show coverage.
    """
    subprocess.call(["coverage", "run", "-m", "pytest"], env=env_with_pythonpath())
    subprocess.call(["coverage", "html"])
    if platform.system() == "Darwin":
        subprocess.call(["open", "htmlcov/index.html"])
    elif platform.system() == "Linux" and "Microsoft" in platform.release():  # on WSL
        subprocess.call(["explorer.exe", r"htmlcov\index.html"])


@cli.command()
def jupyterlab():
    """
    Start a jupyterlab server.
    """
    project_root = get_project_root()
    notebook_dir = project_root / "notebooks"
    notebook_dir.mkdir(exist_ok=True)
    env = env_with_pythonpath()
    subprocess.call([sys.executable, "-m", "jupyterlab", "--notebook-dir", "notebooks/"], env=env)


@cli.command()
def update(upgrade: bool = typer.Option(True, "--upgrade/--no-upgrade")):
    """
    Update the requirements using uv.
    """
    print("Updating requirements via uv...")
    subprocess.call(["uv", "lock", "--upgrade"])


@cli.command()
def clean_build():
    commands = [
        ["rm", "-fr", "build/"],
        ["rm", "-fr", "dist/"],
        ["rm", "-fr", "*.egg-info"],
        ["rm", "-fr", "__pycache__"],
    ]
    for command in commands:
        subprocess.call(command)


@cli.command()
def clean_pyc():
    commands = [
        ["find", ".", "-name", "*.pyc", "-exec", "rm -f {} +"],
        ["find", ".", "-name", "*.pyo", "-exec", "rm -f {} +"],
        ["find", ".", "-name", "*~", "-exec", "rm -f {} +"],
    ]
    for command in commands:
        subprocess.call(command)


@cli.command()
def clean():
    clean_build()
    clean_pyc()


@cli.command()
def docs():
    autogenerated = [
        "cast.api.rst",
        "cast.migrations.rst",
        "cast.rst",
        "cast.templatetags.rst",
        "modules.rst",
    ]
    for rst_name in autogenerated:
        (Path("docs") / rst_name).unlink(missing_ok=True)
    commands = [
        ["sphinx-apidoc", "-o", "docs/", "cast"],
        ["make", "-C", "docs", "clean"],
        ["make", "-C", "docs", "html"],
    ]
    for command in commands:
        subprocess.call(command)
    file_url = "file://" + str(Path("docs/_build/html/index.html").resolve())
    webbrowser.open_new_tab(file_url)


@contextlib.contextmanager
def working_directory(path):
    """Changes working directory and returns to previous on exit."""
    prev_cwd = Path.cwd().absolute()
    try:
        os.chdir(path)
        yield
    finally:
        os.chdir(prev_cwd)


@cli.command()
def production_db_to_local(
    production_host: str = typer.Option("wersdoerfer.de", help="SSH host for the production server."),
    production_ssh_user: str = typer.Option("root", help="SSH user for the production server."),
    production_db_name: str = typer.Option("python-podcast", help="Production PostgreSQL database name."),
    production_db_user: str = typer.Option("postgres", help="Remote system user allowed to dump PostgreSQL."),
    local_db_name: str = typer.Option("python_podcast", help="Local PostgreSQL database name to restore into."),
):
    """
    Fetch a production PostgreSQL dump over SSH and restore it locally.

    Make sure only the database is running using:
      just postgres
    """
    import psutil

    for proc in psutil.process_iter(["pid", "name", "username"]):
        try:
            cmdline = " ".join(proc.cmdline())
            if "honcho" in cmdline:
                print("please stop honcho first and start a single postgres db with just postgres")
                sys.exit(1)
        except (psutil.AccessDenied, psutil.NoSuchProcess, psutil.ZombieProcess):
            # ignore processes that we cannot observe
            pass

    backups_dir = get_project_root() / "backups"
    backups_dir.mkdir(exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d-%H%M%S")
    backup_path = backups_dir / f"{timestamp}_{production_db_name}.sql.gz"

    remote_dump_pipeline = (
        "set -o pipefail; "
        f"sudo -u {shlex.quote(production_db_user)} "
        f"pg_dump --no-owner --no-privileges {shlex.quote(production_db_name)} | gzip -c"
    )
    remote_dump_command = f"bash -lc {shlex.quote(remote_dump_pipeline)}"
    ssh_target = f"{production_ssh_user}@{production_host}"
    print(f"Creating production backup via SSH: {ssh_target}:{production_db_name}")
    try:
        with backup_path.open("wb") as backup_file:
            subprocess.run(["ssh", ssh_target, remote_dump_command], stdout=backup_file, check=True)
    except subprocess.CalledProcessError:
        backup_path.unlink(missing_ok=True)
        raise

    try:
        subprocess.run(["createuser", local_db_name], check=False)
        subprocess.run(["dropdb", "--if-exists", local_db_name], check=True)
        subprocess.run(["createdb", local_db_name], check=True)
        command = f"gunzip -c {shlex.quote(str(backup_path))} | psql {shlex.quote(local_db_name)}"
        print(command)
        subprocess.run(["bash", "-o", "pipefail", "-c", command], check=True)
    except subprocess.CalledProcessError:
        print(f"local restore failed; close open connections to {local_db_name} and rerun")
        print(f"production backup was saved at {backup_path}")
        raise
    print(backup_path)


@cli.command()
def make_local_db_restorable():
    """
    Make a local db restorable by ansible.

    Just print out help atm.
    """
    help = """
        pg_dump python_podcast | gzip > backups/db.staging.psql.gz
        cd deploy
        ansible-playbook restore_database.yml
    """
    print(help)


def deploy(environment):
    """
    Use legacy ansible-playbook flow under deploy/ (kept for reference).
    """
    deploy_root = Path(__file__).parent / "deploy"
    with working_directory(deploy_root):
        subprocess.call(["ansible-playbook", "deploy.yml", "--limit", environment])


_SECTION_HEADER_RE = re.compile(r"^\s*\[.*\]\s*(?:#.*)?$")


def _format_toml_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"Unsupported TOML value type: {type(value)!r}")


def _format_inline_table(table):
    parts = [f"{key} = {_format_toml_value(value)}" for key, value in table.items()]
    return "{ " + ", ".join(parts) + " }"


def _find_table_range(lines, header):
    start_idx = None
    for i, line in enumerate(lines):
        if line.split("#", 1)[0].strip() == header:
            start_idx = i
            break
    if start_idx is None:
        return None, None

    end_idx = len(lines)
    for i in range(start_idx + 1, len(lines)):
        if _SECTION_HEADER_RE.match(lines[i]) and lines[i].lstrip().startswith("["):
            end_idx = i
            break
    return start_idx, end_idx


def _upsert_single_line_entries_in_table(pyproject_text, header, entries):
    lines = pyproject_text.splitlines(keepends=True)
    start_idx, end_idx = _find_table_range(lines, header)

    if start_idx is None:
        if lines and not lines[-1].endswith("\n"):
            lines[-1] = lines[-1] + "\n"
        if lines and lines[-1].strip():
            lines.append("\n")
        lines.append(f"{header}\n")
        for key, value in entries.items():
            lines.append(f"{key} = {value}\n")
        return "".join(lines)

    table_start = start_idx + 1
    table_end = end_idx

    keys = set(entries.keys())
    for i in range(table_end - 1, table_start - 1, -1):
        line = lines[i]
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = re.match(r"^\s*([A-Za-z0-9_.-]+)\s*=", line)
        if not match:
            continue
        if match.group(1) in keys:
            del lines[i]
            table_end -= 1

    insert_at = table_end
    while insert_at > table_start and not lines[insert_at - 1].strip():
        insert_at -= 1

    new_lines = [f"{key} = {value}\n" for key, value in entries.items()]
    lines[insert_at:insert_at] = new_lines
    return "".join(lines)


@cli.command()
def switch_to_dev_environment():
    """
    Switch to development mode using local editable packages.

    Modifies pyproject.toml to use local paths in tool.uv.sources.
    """
    project_root = get_project_root()
    projects_dir = project_root.parent
    pyproject_path = project_root / "pyproject.toml"

    # Define local package mappings
    packages = [
        ("cast-vue", projects_dir / "cast-vue"),
        ("cast-bootstrap5", projects_dir / "cast-bootstrap5"),
        ("django-cast", projects_dir / "django-cast"),
        ("django-indieweb", projects_dir / "django-indieweb"),
    ]

    print("Switching to local development sources in pyproject.toml...")

    sources_modified = False
    updates = {}
    for package_name, package_path in packages:
        if package_path.exists():
            updates[package_name] = _format_inline_table({"path": f"../{package_path.name}", "editable": True})
            print(f"✓ {package_name} -> {package_path}")
            sources_modified = True
        else:
            print(f"Warning: {package_path} does not exist, skipping")

    if sources_modified:
        pyproject_text = pyproject_path.read_text(encoding="utf-8")
        updated = _upsert_single_line_entries_in_table(pyproject_text, "[tool.uv.sources]", updates)
        pyproject_path.write_text(updated, encoding="utf-8")

        print("\nRunning uv sync to apply changes...")
        subprocess.call(["uv", "sync"])

        print("\nDevelopment environment activated!")
        print("Local packages are now installed in editable mode.")
        print("Changes to the source code will be reflected immediately.")
        print("\nIMPORTANT: Remember to run prek hooks before committing!")
        print("To switch back to git sources, run: uv run python commands.py switch-to-git-sources")


@cli.command()
def switch_to_git_sources():
    """
    Switch back to git sources from local development mode.

    Restores original git sources in pyproject.toml.
    """
    project_root = get_project_root()
    pyproject_path = project_root / "pyproject.toml"

    # Define default git sources
    default_sources = {
        "cast-vue": {"git": "https://github.com/ephes/cast-vue"},
        "cast-bootstrap5": {"git": "https://github.com/ephes/cast-bootstrap5"},
        "django-cast": {"git": "https://github.com/ephes/django-cast", "branch": "develop"},
        "django-indieweb": {"git": "https://github.com/ephes/django-indieweb", "branch": "develop"},
    }

    print("Restoring git sources in pyproject.toml...")
    updates = {}
    for package_name, git_source in default_sources.items():
        updates[package_name] = _format_inline_table(git_source)
        print(f"✓ {package_name} -> {git_source}")

    pyproject_text = pyproject_path.read_text(encoding="utf-8")
    updated = _upsert_single_line_entries_in_table(pyproject_text, "[tool.uv.sources]", updates)
    pyproject_path.write_text(updated, encoding="utf-8")

    print("\nRunning uv sync to apply changes...")
    subprocess.call(["uv", "sync", "--reinstall"])

    print("\nSwitched back to git sources!")
    print("All packages are now installed from their git repositories.")


if __name__ == "__main__":
    cli()
