"""Convert legacy episode detail shownotes into structured show-note blocks.

The command is conservative and safe to run repeatedly:

* It only rewrites the ``detail`` body section.
* It only converts ``paragraph`` children whose HTML actually contains shownote
  structure; every other child (``image``, ``audio``, ...) is preserved verbatim.
* Ambiguous content is preserved as a paragraph with a warning rather than being
  converted in a lossy way (see ``pp.show_notes.converter``).
* It is idempotent: a detail that already contains ``show_note_*`` blocks is
  skipped.

By default the command performs a dry run and writes nothing. Use ``--apply`` to
create a Wagtail draft revision and ``--publish`` to publish that revision.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field

from cast.models import Episode
from django.core.management.base import BaseCommand

from python_podcast.pp.show_notes.converter import ConvertedBlock, convert_paragraph_html

SHOW_NOTE_TYPES = frozenset({"show_note_heading", "show_note_link_list", "show_note_sponsor"})


@dataclass
class EpisodeResult:
    slug: str
    pk: int
    status: str  # "changed" | "skipped"
    reason: str = ""
    before_types: list[str] = field(default_factory=list)
    after_types: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    revision_pk: int | None = None


class Command(BaseCommand):
    help = "Convert legacy episode detail shownotes into structured show-note blocks."

    def add_arguments(self, parser):
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Write changes by creating a Wagtail draft revision. Without this flag the command is a dry run.",
        )
        parser.add_argument(
            "--publish",
            action="store_true",
            help="Publish the created revision. Implies --apply.",
        )
        parser.add_argument(
            "--slug",
            action="append",
            dest="slugs",
            default=[],
            metavar="SLUG",
            help="Limit conversion to the episode with this slug. May be given multiple times.",
        )
        parser.add_argument(
            "--force",
            action="store_true",
            help=(
                "Re-convert from the original legacy body (the most recent "
                "unconverted version, taken from revision history if needed), "
                "ignoring the 'already converted' guard. Use to regenerate "
                "conversions after the converter has been improved."
            ),
        )

    def handle(self, *args, **options):
        publish = options["publish"]
        apply = options["apply"] or publish
        force = options["force"]
        slugs = options["slugs"]

        episodes = Episode.objects.all()
        if slugs:
            episodes = episodes.filter(slug__in=slugs)
        episodes = episodes.order_by("pk")

        results = [self._process_episode(episode, apply=apply, publish=publish, force=force) for episode in episodes]

        for result in results:
            self._report(result)

        self._report_summary(results, apply=apply, publish=publish)

    # -- per-episode ----------------------------------------------------
    def _process_episode(self, episode: Episode, *, apply: bool, publish: bool, force: bool) -> EpisodeResult:
        # The detail conversion source: normally the latest revision (the current
        # draft) so the command stays idempotent; with --force, the original
        # legacy body (most recent unconverted version) so a previously converted
        # episode can be regenerated by an improved converter.
        if force:
            raw_top = self._legacy_raw_top(episode)
            if raw_top is None:
                return EpisodeResult(episode.slug, episode.pk, "skipped", reason="no legacy body to re-convert")
        else:
            raw_top = episode.get_latest_revision_as_object().body.raw_data
        detail_blocks = [block for block in raw_top if block["type"] == "detail"]

        if not detail_blocks:
            return EpisodeResult(episode.slug, episode.pk, "skipped", reason="no detail section")

        if not force and self._already_converted(detail_blocks):
            # The latest draft is already converted. When publishing, push that
            # draft live -- but only if the live page is still legacy, i.e. the
            # pending change really is our conversion and not an unrelated draft.
            live_detail = [block for block in episode.body.raw_data if block["type"] == "detail"]
            live_converted = bool(live_detail) and self._already_converted(live_detail)
            if publish and episode.has_unpublished_changes and not live_converted:
                revision = episode.get_latest_revision()
                revision.publish()
                return EpisodeResult(
                    episode.slug,
                    episode.pk,
                    "changed",
                    reason="published existing converted draft",
                    revision_pk=revision.pk,
                )
            return EpisodeResult(episode.slug, episode.pk, "skipped", reason="already converted")

        before_types = [child["type"] for block in detail_blocks for child in block["value"]]

        new_top, after_types, warnings, changed = self._convert_top(raw_top)
        if not changed:
            return EpisodeResult(episode.slug, episode.pk, "skipped", reason="no convertible shownote HTML")

        result = EpisodeResult(
            episode.slug,
            episode.pk,
            "changed",
            before_types=before_types,
            after_types=after_types,
            warnings=warnings,
        )

        if apply:
            # Always edit the latest-revision object so other unpublished draft
            # changes (overview edits, page fields) are preserved. Only the
            # detail section is swapped in -- with --force the converted detail
            # comes from the legacy body while everything else stays current.
            target = episode.get_latest_revision_as_object()
            merged_top = self._merge_detail(target.body.raw_data, new_top)
            target.body = target.body.stream_block.to_python(merged_top)
            revision = target.save_revision()
            result.revision_pk = revision.pk
            if publish:
                revision.publish()

        return result

    @staticmethod
    def _merge_detail(target_raw: list[dict], converted_top: list[dict]) -> list[dict]:
        """Splice the converted detail block(s) into the target's current body.

        Non-detail blocks (``overview`` etc.) are taken from ``target_raw`` so
        they are never reverted, even when the conversion source is an older
        revision (``--force``).
        """
        converted_details = [block for block in converted_top if block["type"] == "detail"]
        merged: list[dict] = []
        index = 0
        for block in target_raw:
            if block["type"] == "detail" and index < len(converted_details):
                converted = converted_details[index]
                merged.append({"type": "detail", "value": converted["value"], "id": block.get("id")})
                index += 1
            else:
                merged.append(block)
        return merged

    @staticmethod
    def _already_converted(detail_blocks: list[dict]) -> bool:
        return any(child["type"] in SHOW_NOTE_TYPES for block in detail_blocks for child in block["value"])

    def _legacy_raw_top(self, episode: Episode) -> list[dict] | None:
        """Return the most recent body that has not yet been converted.

        Prefers the live body when it is still legacy, otherwise scans revisions
        newest-first for the last version whose detail has no ``show_note_*``
        blocks. Returns ``None`` if every version is already converted.
        """
        live = episode.body.raw_data
        live_detail = [block for block in live if block["type"] == "detail"]
        if live_detail and not self._already_converted(live_detail):
            return live

        for revision in episode.revisions.order_by("-created_at"):
            body = revision.content.get("body")
            if body is None:
                continue
            raw = json.loads(body) if isinstance(body, str) else body
            detail = [block for block in raw if block["type"] == "detail"]
            if detail and not self._already_converted(detail):
                return raw
        return None

    def _convert_top(self, raw_top: list[dict]) -> tuple[list[dict], list[str], list[str], bool]:
        new_top: list[dict] = []
        after_types: list[str] = []
        warnings: list[str] = []
        changed = False

        for block in raw_top:
            if block["type"] != "detail":
                new_top.append(block)
                continue

            new_children: list[dict] = []
            for child in block["value"]:
                if child["type"] != "paragraph":
                    new_children.append(child)
                    continue

                conversion = convert_paragraph_html(child["value"])
                if not conversion.changed:
                    new_children.append(child)
                    continue

                changed = True
                warnings.extend(conversion.warnings)
                for converted in conversion.blocks:
                    new_children.append(self._raw_block(converted))

            after_types.extend(grandchild["type"] for grandchild in new_children)
            new_top.append({"type": "detail", "value": new_children, "id": block.get("id")})

        return new_top, after_types, warnings, changed

    @staticmethod
    def _raw_block(converted: ConvertedBlock) -> dict:
        return {"type": converted.type, "value": converted.value, "id": uuid.uuid4().hex}

    # -- reporting ------------------------------------------------------
    def _report(self, result: EpisodeResult) -> None:
        self.stdout.write(f"Episode {result.slug} (pk={result.pk})")
        if result.status == "skipped":
            self.stdout.write(f"  -> skipped: {result.reason}")
            return

        if not result.before_types and result.reason:
            # e.g. publishing an existing converted draft.
            self.stdout.write(f"  -> {result.reason} (revision {result.revision_pk})")
            return

        self.stdout.write(f"  before: {', '.join(result.before_types) or '(empty)'}")
        self.stdout.write(f"  after:  {', '.join(result.after_types) or '(empty)'}")
        for warning in result.warnings:
            self.stdout.write(f"  warning: {warning}")
        if result.revision_pk is not None:
            self.stdout.write(f"  -> changed (revision {result.revision_pk})")
        else:
            self.stdout.write("  -> would change (dry run)")

    def _report_summary(self, results: list[EpisodeResult], *, apply: bool, publish: bool) -> None:
        changed = sum(1 for result in results if result.status == "changed")
        skipped = sum(1 for result in results if result.status == "skipped")
        with_warnings = sum(1 for result in results if result.warnings)

        self.stdout.write("")
        self.stdout.write(f"Summary: {changed} changed, {skipped} skipped, {with_warnings} with warnings")
        if not apply:
            self.stdout.write("Dry run: no changes written. Re-run with --apply to create revisions.")
        elif publish:
            self.stdout.write("Applied and published revisions.")
        else:
            self.stdout.write("Applied: created draft revisions (not published).")
