- hosts: all
  tasks:
    - name: "Include secret vars"
      include_vars: secrets.yml

    - name: "Include staging secret vars"
      include_vars: secrets_staging.yml
      when: deploy_environment == "staging"

    - name: "Include production secret vars"
      include_vars: secrets_production.yml
      when: deploy_environment == "production"

    - name: "Include public vars"
      include_vars: vars.yml

    - name: "Set timestamp of the backup"
      set_fact:
        now: '{{ lookup("pipe", "date +%F-%T") }}'

    - name: "Set backup file name"
      set_fact:
        backup_file: "{{ now }}_{{ postgres_database }}.sql.gz"

    - name: "Show backup file name"
      ansible.builtin.debug:
        msg: "{{ backup_file }}"

    - name: Backup directory
      ansible.builtin.file:
        path: "{{ postgres_backup_dir }}"
        mode: 0777
        owner: postgres
        state: directory

    - name: "Backup the database"
      community.postgresql.postgresql_db:
        state: dump
        name: "{{ postgres_database }}"
        target: "{{ postgres_backup_dir }}/{{ backup_file }}"
      become: yes
      become_user: postgres

    - name: "Fetch backup from the server"
      fetch:
        src: "{{ postgres_backup_dir }}/{{ backup_file }}"
        dest: "{{ playbook_dir }}/../backups/{{ backup_file }}"
        flat: yes
