- hosts: production
  tasks:
    - name: Install required build packages
      apt:
        name: [
          "build-essential", "libssl-dev", "zlib1g-dev", "libgdbm-dev", "libnss3-dev", "libreadline-dev", "libbz2-dev", "libsqlite3-dev", "libncurses5-dev", "libffi-dev", "liblzma-dev", "curl",
        ]

    - name: Ensure python source directory exists
      file:
        path: /opt/python
        state: directory

    - name: Download python source
      unarchive:
        src: https://www.python.org/ftp/python/3.11.0/Python-3.11.0.tar.xz
        dest: /opt/python
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Run python configure script
      command: ./configure --enable-optimizations
      args:
        chdir: /opt/python

    - name: Run python make
      command: make -j 4
      args:
        chdir: /opt/python

    - name: Run python make install
      command: make altinstall
      args:
        chdir: /opt/python
