---
# public variables for deployment
project_name: "python-podcast"
postgres_database: "{{ project_name }}"
postgres_user: "{{ project_name }}"
home_path: "/home/{{ username }}"
site_path: "{{ home_path }}/site"
django_cache_location: "{{ site_path }}/cache"
global_python: python3.11
venv_bin: "{{ site_path }}/venv/bin"
python: "{{ venv_bin }}/python"
pip_sync: "{{ venv_bin }}/pip-sync"
default_path: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
port: 10014
django_settings_module: "config.settings.production"
traefik_config_dir: "/etc/traefik/dynamic"
traefik_config_path: "{{ traefik_config_dir }}/{{ project_name }}.traefik.yml"
systemd_unit_path: "/etc/systemd/system/{{ project_name }}.service"
gunicorn_number_of_workers: 4
